### ISSUE TITLE
Need help 

### ISSUE THREAD

**Issue by thelearner049** [SquareRooT1/ShockBandReactNative#1]
Hi bro, i was looking for this project since very long and i recently found that you've done it already. 
I want to make this alarm watch bro but don't exactly know how, Can you please help me with that?

**Comment by muhammedkanlidere** [comment]
Hi,
Project contains two part, first is software managing the alarm and sending
signal to hardware, and second part is hardware after it gets signal doing
the shock which area are you struggling with?

**Comment by thelearner049** [comment]
Mainly it's the Hardware where I'm confused like which components are being
used and how they are arranged in the circuit cuz I want to make it small
so that it can be wearable in hand.

**Comment by muhammedkanlidere** [comment]
It is been a while i do not remember exactly all the pieces but,
in short, we used electric prank toys
https://www.amazon.com/Cooplay-Shocking-Hardcover-Electric-Halloween/dp/B00UIX1SH8/ref=sr_1_1?keywords=shock+gum&qid=1688455813&sr=8-1
The transistor inside this toy is really small so you can take it out. if
you adjust the electrical current you can have different power of shock.
to be able to trigger you can either use Bluetooth module or nodemcu &
esp8266 wifi module to send a command from the software rest is a basic
circuit

**Comment by muhammedkanlidere** [comment]
You can also have a look at the hardware we used 6 years ago,in this video https://youtu.be/tBnUwieGfJA?t=348 our goal wasn't to make it a small product as it was a fun hobby project.

**Comment by thelearner049** [comment]
Thanks for the help, I'll definitely check it out!
